### PR TITLE
Update Chinese translation for 1.25.0

### PR DESCRIPTION
**Pull request by Genglxy**
Update to the latest version.

### CODE REVIEW

**Comment by Genglxy** [comment]
Can you give me some contextual information about "ticket"? The phrase "download account ticket" or "download ticket" rarely appears in Chinese, does it have another meaning here, such as "information"?

**Comment by Genglxy** [comment]
Well... I found some relevant information :
https://wiibrew.org/wiki/Ticket

Now that I understand what this means, can I translate it as "verification information" or "digital signature", or should I keep the English original? I found a translation for "digital signature" on a Chinese website, but otherwise, the original English text is used directly. I think it would be better to have a translation, can I have your opinion?

**Comment by Genglxy** [comment]
Of course, some sites choose to translate the tickets as title.tik files, which I don't think is appropriate. What do you think?

**Comment by Fs00** [comment]
IMO in this case is probably better to leave it untranslated since the term "ticket" has a very specific meaning when talking about Nintendo consoles. I fear that translating this term will make things more difficult for users when they search for it on the Internet. If you found other Chinese texts mentioning "ticket" as-is, I would definitely go for it.

PS: I'm not a collaborator of this repo anymore, so I won't review or merge this. I was just stumbling around :)

**Comment by Genglxy** [comment]
> IMO in this case it is probably better to leave it untranslated since the term "ticket" has a very specific meaning when talking about Nintendo consoles. I fear that translating this term will make things more difficult for users when they search for it on the Internet. If you found other Chinese texts mentioning "ticket" as-is, I would definitely go for it.
> 
> Also, I agree with you that "title.tik files" wouldn't be a proper translation here, since they refer to a particular kind of ticket if I recall.
> 
> PS: I'm not a collaborator of this repo anymore, so I won't review or merge this. I was just stumbling around :)

Long time no see! I think you have a point, so I just did some more in-depth searching and finally found that in 2016, some influential people in a forum had translated ticket as "票证" and put "ticket" in parentheses after it. "(The common meaning of ticket itself has a variety of expressions with similar meanings in Chinese, and different expressions sometimes show different results in searches, for example, "wiiu 票据" will bring up many shopping sites 😂). This expression can also be found on a few other websites. Thank you very much! I think translating it to “票证” and attaching it in English will solve most of the confusion, thanks for your help.

**Pull request closed without merging**
