### PR TITLE
Added Hebrew translation

### PR DESCRIPTION
**Pull request by iliya8801**
Added Hebrew translation.

not a 100% yet on the complicated technical terminology.

Also I would like to ask if there's a plan for integrating Right To Left text direction for cemu.
If not, I would have to make some changes to the text order. Because in some cases the text flips after an English word.

### CODE REVIEW

**Comment by Hackjjang** [comment]
You must register the source file, not the compiled binary file.

**Comment by iliya8801** [comment]
> You must register the source file, not the compiled binary file.

Hi, there you go. I uploaded the PO file

**Comment by Exzap** [comment]
Can you remove the extra files, only `resources/he/cemu.po` is needed

**Comment by iliya8801** [comment]
> Can you remove the extra files, only `resources/he/cemu.po` is needed

done.

**Comment by Exzap** [comment]
Oh you removed ALL the files. I meant just the ones you added besides `resources/he/cemu.po`.

**Comment by iliya8801** [comment]
> Oh you removed ALL the files. I meant just the ones you added besides `resources/he/cemu.po`.

I deleted everyting except resources/he/cemu.po.

**Comment by Exzap** [comment]
Sorry if I have been unclear. But the problem is that when you delete the files, your pull request will contain those deletions and if I merge it, the files will be deleted on this repository too.

What you should have done is add **only** `resources/he/cemu.po` and not modify or delete any other files.

Anyway I have manually committed your language file (9f793ee8a02f75bfaae0fde0d0a4c6731bfcb942) and will close this pull request now.

**Comment by iliya8801** [comment]
> Sorry if I have been unclear. But the problem is that when you delete the files, your pull request will contain those deletions and if I merge it, the files will be deleted on this repository too.
> 
> What you should have done is add **only** `resources/he/cemu.po` and not modify or delete any other files.
> 
> Anyway I have manually committed your language file ([9f793ee](https://github.com/cemu-project/Cemu-Language/commit/9f793ee8a02f75bfaae0fde0d0a4c6731bfcb942)) and will close this pull request now.

Thank you for your help! i'm not that familiar with git.

**Pull request closed without merging**
